module.exports = {
	printWidth: 110,
  tabWidth: 2,
	semi: true,
	singleQuote: true,
	allowSingleLine: true,
	quoteProps: 'as-needed',
	jsxSingleQuote: false,
	trailingComma: 'es5',
	bracketSpacing: true,
	bracketSameLine: true,
	arrowParens: 'avoid',
	proseWrap: 'preserve',
	htmlWhitespaceSensitivity: 'css',
	vueIndentScriptAndStyle: false,
	endOfLine: 'lf',
	embeddedLanguageFormatting: 'auto',
	useTabs: true,
	eslintIntegration: true,
};
